name: Update WMCO to support Kubernetes bump
description: Issue to track Kubernetes bump dependencies
assignees:
  - "@openshift/openshift-team-windows-containers"
body:
  - type: markdown
    attributes:
      value: |
        **Issue for tracking Kubernetes bump**
        
        In order to bump Windows Machine Config Operator to support Kubernetes <version> there are a few dependencies we rely on making the bump first.
        This issue is meant to help track all dependencies and the status of their bumps.
        
        **Order of dependency bumps:**
  - type: checkboxes
    id: checklist
    attributes:
      label: Step 1 - Upgrade go version
      description: Go version needs to be upgraded to match rest of the OpenShift and k8s upgraded components.
      options:
        - label: Go version is upgraded for WMCO and WMCB branches
          required: true
