---
name: Issue for k8s bump
description: Issue to track k8s bump dependencies
assignees:
  - "@openshift/openshift-team-windows-containers"
body:
  - type: markdown
    attributes:
      value: |
        Meta Issue for k8s bump
        In order to bump Windows Machine Config Operator to support Kubernetes 1.25 there are a few dependencies we rely on making the bump first.
        This issue is meant to help track all dependencies and the status of their bumps.
        Order of dependency bumps:
        
