**Meta Issue for k8s 1.25 bump**

In order to bump Windows Machine Config Operator to support Kubernetes 1.25 there are a few dependencies we rely on making the bump first.

This issue is meant to help track all dependencies and the status of their bumps.

**Order of dependency bumps:**
